name: 'Retry Center'
description: '统一的重试中心'

inputs:
  step_name:
    description: '步骤名称'
    required: true
  command:
    description: '要执行的命令'
    required: true

runs:
  using: 'node20'
  main: 'index.js'
