name: 'Retry Center'
description: '统一的重试中心'

inputs:
  step_name:
    description: '步骤名称'
    required: true
  command:
    description: '要执行的命令'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 执行命令
      shell: bash
      run: |
        echo "执行步骤: ${{ inputs.step_name }}"
        echo "执行命令: ${{ inputs.command }}"
        eval "${{ inputs.command }}"
