name: Deploy to Production

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    uses: MoseLu/axi-deploy/.github/workflows/ssh-deploy.yml@master
    with:
      # 部署配置
      source_path: './dist'
      target_path: '/www/wwwroot/my-app'
      exclude_files: '.git,node_modules,.env'
      commands: |
        cd /www/wwwroot/my-app
        npm install --production
        pm2 restart my-app
        sudo systemctl reload nginx 