name: Simple Deploy Trigger

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 触发部署
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DEPLOY_CENTER_PAT }}
          script: |
            const { data: response } = await github.rest.actions.createWorkflowDispatch({
              owner: 'your-org',
              repo: 'axi-deploy',
              workflow_id: 'deploy.yml',
              ref: 'main',
              inputs: {
                project: 'my-simple-app',
                lang: 'node',
                artifact_id: '123456789',  // 需要替换为实际的构建产物ID
                deploy_path: '/www/wwwroot/my-simple-app',
                start_cmd: 'cd /www/wwwroot/my-simple-app && npm ci --production && pm2 reload app',
                caller_repo: '${{ github.repository }}',
                caller_branch: '${{ github.ref_name }}',
                caller_commit: '${{ github.sha }}'
              }
            });
            console.log('✅ 部署已触发:', response); 