name: Parse Secrets

description: "解析部署密钥 - 从部署密钥中提取服务器配置信息"

on:
  workflow_call:
    inputs:
      deploy_secrets:
        required: true
        type: string
        description: "部署密钥"
    outputs:
      server_host:
        description: "服务器地址"
        value: ${{ jobs.parse.outputs.server_host }}
      server_port:
        description: "服务器端口"
        value: ${{ jobs.parse.outputs.server_port }}
      server_user:
        description: "服务器用户"
        value: ${{ jobs.parse.outputs.server_user }}
      server_key:
        description: "服务器密钥"
        value: ${{ jobs.parse.outputs.server_key }}
      deploy_center_pat:
        description: "部署中心PAT"
        value: ${{ jobs.parse.outputs.deploy_center_pat }}

jobs:
  parse:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      packages: read
    outputs:
      server_host: ${{ steps.parse-secrets.outputs.server_host }}
      server_port: ${{ steps.parse-secrets.outputs.server_port }}
      server_user: ${{ steps.parse-secrets.outputs.server_user }}
      server_key: ${{ steps.parse-secrets.outputs.server_key }}
      deploy_center_pat: ${{ steps.parse-secrets.outputs.deploy_center_pat }}
    
    steps:
      - name: 解析部署密钥
        id: parse-secrets
        run: |
          echo "🔍 解析部署密钥..."
          
          # 从输入参数获取部署密钥
          DEPLOY_SECRETS='${{ inputs.deploy_secrets }}'
          
          # 检查是否为base64编码
          if echo "$DEPLOY_SECRETS" | base64 -d &>/dev/null; then
            echo "📦 检测到base64编码的部署密钥，正在解码..."
            DEPLOY_SECRETS=$(echo "$DEPLOY_SECRETS" | base64 -d)
          fi
          
          # 使用jq解析JSON配置
          if echo "$DEPLOY_SECRETS" | jq -e '.' >/dev/null 2>&1; then
            SERVER_HOST=$(echo "$DEPLOY_SECRETS" | jq -r '.SERVER_HOST // empty')
            SERVER_PORT=$(echo "$DEPLOY_SECRETS" | jq -r '.SERVER_PORT // empty')
            SERVER_USER=$(echo "$DEPLOY_SECRETS" | jq -r '.SERVER_USER // empty')
            SERVER_KEY=$(echo "$DEPLOY_SECRETS" | jq -r '.SERVER_KEY // empty')
            DEPLOY_CENTER_PAT=$(echo "$DEPLOY_SECRETS" | jq -r '.DEPLOY_CENTER_PAT // empty')
          else
            echo "🚨 无法解析部署密钥JSON格式"
            echo "🔍 部署密钥内容预览:"
            echo "$DEPLOY_SECRETS" | head -c 100
            exit 1
          fi
          
          # 验证必需参数
          if [ "$SERVER_HOST" = "null" ] || [ -z "$SERVER_HOST" ]; then
            echo "🚨 缺少必需的SERVER_HOST参数"
            exit 1
          fi
          if [ "$SERVER_PORT" = "null" ] || [ -z "$SERVER_PORT" ]; then
            echo "🚨 缺少必需的SERVER_PORT参数"
            exit 1
          fi
          if [ "$SERVER_USER" = "null" ] || [ -z "$SERVER_USER" ]; then
            echo "🚨 缺少必需的SERVER_USER参数"
            exit 1
          fi
          if [ "$SERVER_KEY" = "null" ] || [ -z "$SERVER_KEY" ]; then
            echo "🚨 缺少必需的SERVER_KEY参数"
            exit 1
          fi
          if [ "$DEPLOY_CENTER_PAT" = "null" ] || [ -z "$DEPLOY_CENTER_PAT" ]; then
            echo "📝 DEPLOY_CENTER_PAT参数未提供，将使用内置GITHUB_TOKEN"
            DEPLOY_CENTER_PAT=""
          fi
          
          # 设置输出 - 对于简单字符串使用普通输出语法
          echo "server_host=$SERVER_HOST" >> $GITHUB_OUTPUT
          echo "server_port=$SERVER_PORT" >> $GITHUB_OUTPUT
          echo "server_user=$SERVER_USER" >> $GITHUB_OUTPUT
          
          # 对于包含换行符的SERVER_KEY，使用多行输出语法
          {
            echo 'server_key<<EOF' >> $GITHUB_OUTPUT
            echo "$SERVER_KEY" >> $GITHUB_OUTPUT
            echo 'EOF' >> $GITHUB_OUTPUT
          }
          
          # 对于PAT，如果为空则使用空字符串，否则使用多行输出语法
          if [ -n "$DEPLOY_CENTER_PAT" ]; then
            {
              echo 'deploy_center_pat<<EOF' >> $GITHUB_OUTPUT
              echo "$DEPLOY_CENTER_PAT" >> $GITHUB_OUTPUT
              echo 'EOF' >> $GITHUB_OUTPUT
            }
          else
            echo "deploy_center_pat=" >> $GITHUB_OUTPUT
          fi
          
          echo "✅ 部署密钥解析完成"
          echo "📋 服务器信息:"
          echo "- 主机: $SERVER_HOST"
          echo "- 端口: $SERVER_PORT"
          echo "- 用户: $SERVER_USER"
          echo "🔍 PAT调试信息:"
          echo "- PAT长度: $(echo "$DEPLOY_CENTER_PAT" | wc -c)"
          echo "- PAT是否为空: $([ -z "$DEPLOY_CENTER_PAT" ] && echo '是' || echo '否')"
          echo "- PAT是否为null: $([ "$DEPLOY_CENTER_PAT" = "null" ] && echo '是' || echo '否')"
          echo "- PAT前10个字符: ${DEPLOY_CENTER_PAT:0:10}..."
