name: SSH Command

on:
  workflow_call:
    inputs:
      commands:
        description: '要执行的命令'
        required: true
        type: string
      timeout:
        description: 'SSH连接超时时间(秒)'
        required: false
        type: string
        default: '300'
    outputs:
      command_status:
        description: '命令执行状态'
        value: ${{ jobs.execute.outputs.status }}
      command_output:
        description: '命令输出'
        value: ${{ jobs.execute.outputs.output }}

jobs:
  execute:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.execute.outputs.status }}
      output: ${{ steps.execute.outputs.output }}
    
    steps:
      - name: 设置SSH环境
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # 配置SSH选项，跳过主机密钥验证
          cat > ~/.ssh/config << EOF
          Host ${{ secrets.SERVER_HOST }}
            HostName ${{ secrets.SERVER_HOST }}
            Port ${{ secrets.SERVER_PORT }}
            User ${{ secrets.SERVER_USER }}
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
          EOF
          chmod 600 ~/.ssh/config
          
      - name: 测试SSH连接
        run: |
          echo "测试连接到: ${{ secrets.SERVER_HOST }}"
          ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "echo 'SSH连接测试成功'"
          
              - name: 执行命令
          id: execute
          run: |
            echo "执行命令: ${{ inputs.commands }}"
            OUTPUT=$(ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "${{ inputs.commands }}" 2>&1)
            EXIT_CODE=$?
          
          echo "命令输出:"
          echo "$OUTPUT"
          
          if [ $EXIT_CODE -eq 0 ]; then
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "status=failed" >> $GITHUB_OUTPUT
          fi
          
          echo "output<<EOF" >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: 清理SSH密钥
        if: always()
        run: |
          rm -f ~/.ssh/id_rsa
          rm -f ~/.ssh/known_hosts 