name: Test SSH Connection

on:
  workflow_dispatch:
    inputs:
      caller_repo:
        description: '调用者仓库'
        required: true
        type: string
      caller_branch:
        description: '调用者分支'
        required: true
        type: string
      caller_commit:
        description: '调用者提交'
        required: true
        type: string

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 测试SSH连接
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            echo "✅ SSH连接测试成功!"
            echo "服务器信息:"
            echo "- 主机: ${{ secrets.SERVER_HOST }}"
            echo "- 端口: ${{ secrets.SERVER_PORT }}"
            echo "- 用户: ${{ secrets.SERVER_USER }}"
            echo "- 当前时间: $(date)"
            echo "- 系统信息: $(uname -a)"
            echo "- 磁盘空间: $(df -h /)"
            echo "- 内存使用: $(free -h)"
            
      - name: 测试完成
        run: |
          echo "✅ 连接测试完成!"
          echo "调用者: ${{ github.event.inputs.caller_repo }}@${{ github.event.inputs.caller_branch }}"
          echo "提交: ${{ github.event.inputs.caller_commit }}" 