name: Test Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 测试步骤
        run: |
          echo "✅ 测试工作流正常运行"
          echo "当前时间: $(date)"
          echo "分支: ${{ github.ref }}"
          echo "提交: ${{ github.sha }}" 