name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: 设置SSH环境
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # 配置SSH选项，跳过主机密钥验证
          cat > ~/.ssh/config << EOF
          Host ${{ secrets.SERVER_HOST }}
            HostName ${{ secrets.SERVER_HOST }}
            Port ${{ secrets.SERVER_PORT }}
            User ${{ secrets.SERVER_USER }}
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
          EOF
          chmod 600 ~/.ssh/config
          
      - name: 测试SSH连接
        run: |
          echo "测试连接到 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_PORT }}"
          
          # 测试基本连接
          ssh -o ConnectTimeout=10 ${{ secrets.SERVER_HOST }} "echo 'SSH连接测试成功'"
          
          # 获取系统信息
          echo "系统信息:"
          ssh ${{ secrets.SERVER_HOST }} "uname -a"
          
          # 获取磁盘空间
          echo "磁盘空间:"
          ssh ${{ secrets.SERVER_HOST }} "df -h"
          
          # 获取内存信息
          echo "内存信息:"
          ssh ${{ secrets.SERVER_HOST }} "free -h"
          
          # 测试应用目录权限
          echo "应用目录权限:"
          ssh ${{ secrets.SERVER_HOST }} "ls -la /www/wwwroot"
          
      - name: 清理SSH密钥
        if: always()
        run: |
          rm -f ~/.ssh/id_rsa
          rm -f ~/.ssh/known_hosts 